server:
  port: 8088

spring:
  profiles: dev




eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:1234@localhost:8761/eureka
    fetchRegistry: true



logging:
  level:
    reactor:
      ipc:
        netty:
          channel:
            ContextHandler: info
        http:
          client:
            HttpClient: info

---

server:
  port: 8090

spring:
  profiles: tst




eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:1234@localhost:8761/eureka
    fetchRegistry: true



logging:
  level:
    reactor:
      ipc:
        netty:
          channel:
            ContextHandler: info
        http:
          client:
            HttpClient: info
