
server:
  port: ${PORT:8000}


spring:  
  application:
    name: helloworld-service

message: Hello gun /dan. ....




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/    
      
      
      
management:
  security:
    enabled: false